### ISSUE TITLE
tilde file in FaradayRF-Hardware/EngineeringDocs/

### ISSUE THREAD

**Issue by herrold** [FaradayRF/FaradayRF-Hardware#24]
which appears to hge an editting remnant

Perhaps in addition to removing it, add a .gitignore rule

**Comment by kb1lqc** [comment]
Thanks @herrold ! I removed the file and updated .gitignore for excel temporary files. Thank you for noticing this and bringing it to my attention.

Fixed in https://github.com/FaradayRF/FaradayRF-Hardware/commit/544a476372e39b63fae3422f92af0d5fcfd556b4 latest master.
