### ISSUE TITLE
Synchronous/Asynchronous CC430 Radio Support 

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/FaradayRF-Hardware#6]
# Overview

It is likely that in the future Faraday will split into two main projects:
- A smart node digital radio with radio and communication processes controls on the CC430
- A (mostly) dumb radio module that allows a more powerful processor perform the communications such as a Raspberry Pi. Interactions with Faraday in this mode would largely be that of a raw modem interface through UART/SPI/CC1101 GDx pins

Texas Instruments provides a basic overview of the radio operations possible with the CC430: [http://www.ti.com/lit/an/slaa465c/slaa465c.pdf](http://www.ti.com/lit/an/slaa465c/slaa465c.pdf)

The example RF code is located here: [http://www.ti.com/lit/zip/slac525](http://www.ti.com/lit/zip/slac525)
## Actions

Since all the default port mapping is used for RF GDx pins and it's a secondary function we should implement port mapping. Port mapping is supported on P1, P2, and P3. We should swap 3 of the GPIO pins using port 4 with port 3 pins to allow a GPIO pin to become an RF GD0 pin.

![image](https://cloud.githubusercontent.com/assets/339144/19631011/9fbdb274-994a-11e6-9689-c0b933109c7b.png)

Swap with basic I/O pins used on GPS and other devices:

![image](https://cloud.githubusercontent.com/assets/339144/19631015/af259740-994a-11e6-9962-61c71bf6fd70.png)

Recommend swapping:

4.0 <-> 3.2
4.1 <-> 3.3
4.2 <-> 3.4

This **Should** allow for low risk swapping and peripheral operation while allowing a port mapped GDx signals to the external pins.
# Details
## Hardware Packet Handling (Less Than/Greater Than FIFO)

No changes needed, all of this is handled in the firmware. Key points:
- Really simple 64 byte FIFO operation
- Capability to have unlimited packet size operation
- Must still use general packet hardware structure and sync headers
## Synchronous/Asynchronous Operations

Synchronous/Asynchronous operation allows for direct access to the CC1101 radio core. This allows for the most flexibility in radio protocols as well as the ability to perform low level protocol processing on a more powerful platform.

![image](https://cloud.githubusercontent.com/assets/339144/19630266/afba8e0e-993b-11e6-9792-8377b9d61c44.png)
### Asynchronous

Requires the use of internal timers.

![image](https://cloud.githubusercontent.com/assets/339144/19630240/1de4670c-993b-11e6-8dff-544c442bfc50.png)

![image](https://cloud.githubusercontent.com/assets/339144/19630241/26643902-993b-11e6-9af9-e98d5aa831b5.png)

![image](https://cloud.githubusercontent.com/assets/339144/19630243/2dab5416-993b-11e6-83cc-a374f53db700.png)
### Synchronous

![image](https://cloud.githubusercontent.com/assets/339144/19630246/386f1806-993b-11e6-941c-100ef8db41c3.png)

![image](https://cloud.githubusercontent.com/assets/339144/19630249/3e859634-993b-11e6-8ac4-6abde07632ff.png)

![image](https://cloud.githubusercontent.com/assets/339144/19630252/49f65670-993b-11e6-8957-87d8e1f6857d.png)
# Port Mapping

![image](https://cloud.githubusercontent.com/assets/339144/19630397/bfca9eda-993e-11e6-82d5-26f4a7de0a09.png)

![image](https://cloud.githubusercontent.com/assets/339144/19630417/18e8c550-993f-11e6-8d0f-00052dacd1f4.png)

![image](https://cloud.githubusercontent.com/assets/339144/19630446/40183ba6-993f-11e6-81b0-b4ac7024b23e.png)

![image](https://cloud.githubusercontent.com/assets/339144/19630449/47e9a7a2-993f-11e6-80cd-125b02820f4c.png)
# Radio GD0 Pins

![image](https://cloud.githubusercontent.com/assets/339144/19630496/706e87a0-9940-11e6-98df-ee0a63859bbf.png)

![image](https://cloud.githubusercontent.com/assets/339144/19630499/7ce16412-9940-11e6-9e1c-e9f4e1a5f921.png)

![image](https://cloud.githubusercontent.com/assets/339144/19630500/840e46b0-9940-11e6-9936-3c76610eccc0.png)
# Examples

Clock timer output to 2.7
Data output 2.6

![image](https://cloud.githubusercontent.com/assets/339144/19630998/557abc52-994a-11e6-9180-dd75560842c2.png)

![image](https://cloud.githubusercontent.com/assets/339144/19631002/67309f98-994a-11e6-9740-e0c5d64d2a74.png)

The CC430 header file snippet above shows Port 3 but Port 2 is the same.

**Comment by kb1lqc** [comment]
Upon inspection, I'd much rather use signals already traveling to the general CC1190 and GPIO pin area so I minimally affect my routing scheme. This means initially I'd like to perform the following IO changes:
- P3.0 to P4.5
- P3.1 to P4.6
- P3.2 to P4.7

This forces the CC1190 control signals to be moved over to GPIO channels. Since these signals generally route to the same area of the PCB this then results in minimal impact to the design.

**Comment by kb1lqd** [comment]
@kb1lqc OK that makes sense. I should double check that all P4 GPIO do infact work as intended.

**Comment by kb1lqc** [comment]
OK I updated and swapped the mentioned P3 and P4 signals. This was much easier to route since the channels all went to the same area of the PCB. This was changed in 4786a6094c6b3ada832c1a492106f61978195773.

**Comment by kb1lqc** [comment]
Closing this issue as it was addressed in Issue #1
